# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='user',
        ),
        migrations.AddField(
            model_name='travel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='exam.User'),
            preserve_default=False,
        ),
    ]
